[package]
name = "anchor_modularized_program"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
anchor-syn = "0.31"
proc-macro2 = "1"
quote = "1"
syn = "1"

[dev-dependencies]
test_program = { path = "./tests/test_program" }
